# Generated by Django 2.2.4 on 2019-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('second', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
